//! The `nixnas.config` model — the TUI's OWN settings (where the operator's flake
//! lives and how to build/flash it). The machine's actual configuration (hostname,
//! pools, unlock members, Secure Boot, TPM2) is Nix — declared in the operator's
//! host overlay, NOT here. This file holds only what the TUI itself consumes.

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Config {
    /// Directory holding the flake that composes nixnas (the private host overlay).
    /// Relative paths resolve against this config file's directory.
    #[serde(default = "default_flake_dir")]
    pub flake_dir: String,

    /// Optional sops-encrypted tar archive of the Secure Boot PKI directory
    /// (sbctl layout: PK/KEK/db keypairs). Decrypted at build time (never written
    /// outside RAM-backed tmp) and injected into the image at /nix/lanzaboote/pki,
    /// so the box signs UKIs with a STABLE operator identity from day one and
    /// across reflashes. None = lanzaboote's first-boot autogenerated keys
    /// (identity changes on every reflash — enroll anew in firmware each time).
    #[serde(default)]
    pub sb_keys_sops: Option<String>,

    /// MiB of RAM for the disko image-builder VM (None = disko's default).
    #[serde(default)]
    pub build_memory_mib: Option<u32>,
}

fn default_flake_dir() -> String {
    ".".to_string()
}

impl Default for Config {
    fn default() -> Self {
        Config {
            flake_dir: default_flake_dir(),
            sb_keys_sops: None,
            build_memory_mib: None,
        }
    }
}

/// The directory a config path lives in. `Path::parent()` returns `Some("")` for a
/// bare relative filename — normalise that to "." (an empty path breaks
/// `Command::current_dir`).
pub fn config_dir(config_path: &Path) -> PathBuf {
    match config_path.parent() {
        Some(p) if !p.as_os_str().is_empty() => p.to_path_buf(),
        _ => PathBuf::from("."),
    }
}

impl Config {
    pub fn load(path: &Path) -> Result<Config> {
        if !path.exists() {
            return Ok(Config::default());
        }
        let text = std::fs::read_to_string(path)
            .with_context(|| format!("reading {}", path.display()))?;
        toml::from_str(&text).with_context(|| format!("parsing {}", path.display()))
    }

    pub fn save(&self, path: &Path) -> Result<()> {
        let text = toml::to_string_pretty(self).context("serialising config")?;
        std::fs::write(path, text).with_context(|| format!("writing {}", path.display()))
    }

    /// The flake directory, resolved against the config file's own directory.
    pub fn resolved_flake_dir(&self, config_path: &Path) -> PathBuf {
        let flake = Path::new(&self.flake_dir);
        if flake.is_absolute() {
            flake.to_path_buf()
        } else {
            config_dir(config_path).join(flake)
        }
    }
}
