//! The `nixnas.config` model — the TUI's OWN settings (where the operator's flake
//! lives and how to build/flash it). The machine's actual configuration (hostname,
//! pools, unlock members, Secure Boot, TPM-gated SSH) is Nix — declared in the operator's
//! host overlay, NOT here. This file holds only what the TUI itself consumes.

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Config {
    /// Directory holding the flake that composes nixnas (the private host overlay).
    /// Relative paths resolve against this config file's directory.
    #[serde(default = "default_flake_dir")]
    pub flake_dir: String,

    /// Optional sops-encrypted tar archive of the Secure Boot PKI directory
    /// (sbctl layout: PK/KEK/db keypairs). Decrypted at build time (never written
    /// outside RAM-backed tmp) and injected into the image at /nix/lanzaboote/pki,
    /// so the box signs UKIs with a STABLE operator identity from day one and
    /// across reflashes. None = lanzaboote's first-boot autogenerated keys
    /// (identity changes on every reflash — enroll anew in firmware each time).
    #[serde(default)]
    pub sb_keys_sops: Option<String>,

    /// MiB of RAM for the disko image-builder VM (None = disko's default).
    #[serde(default)]
    pub build_memory_mib: Option<u32>,

    /// The flake attribute that builds the STICK image script (`nix build .#<attr>`).
    /// Default `imageScript` — a `usb`-mode host's appliance image. A HOT-mode setup
    /// (docs/HOT-MODE.md) flashes its RESCUE system's image instead: either keep the
    /// flake's `imageScript` pointing at the rescue host, or expose a second attribute
    /// (e.g. `rescueImageScript`) and name it here. The hot MAIN is never flashed.
    ///
    /// This is the FIXED-SIZE fallback path: it builds whatever `imageSizeGiB` the host
    /// bakes in. Set `host_attr` (below) to unlock the SIZED build paths instead.
    #[serde(default = "default_image_attr")]
    pub image_attr: String,

    /// The `nixosConfigurations.<name>` attribute of the host whose stick image to build
    /// (e.g. "my-appliance"). Setting this enables the DEVICE-SIZED build paths: because
    /// disko bakes `disk.imageSize` into `qemu-img create` and exposes no runtime size flag,
    /// the TUI re-evaluates this config with `extendModules` overriding
    /// `nixnas.boot.usb.imageSizeGiB`, so the built `.raw` is sized to the target — exact-fit
    /// to a picked stick ("Build & Flash"), or a minimal reusable size ("Build image").
    /// Its image script is `nixosConfigurations.<host_attr>.config.system.build.diskoImagesScript`.
    /// Distinct from `image_attr`, which names a flake OUTPUT. None (the default) → no sizing:
    /// every build falls back to the fixed-size `.#<image_attr>` output above.
    #[serde(default)]
    pub host_attr: Option<String>,
}

fn default_flake_dir() -> String {
    ".".to_string()
}

fn default_image_attr() -> String {
    "imageScript".to_string()
}

impl Default for Config {
    fn default() -> Self {
        Config {
            flake_dir: default_flake_dir(),
            sb_keys_sops: None,
            build_memory_mib: None,
            image_attr: default_image_attr(),
            host_attr: None,
        }
    }
}

/// The directory a config path lives in. `Path::parent()` returns `Some("")` for a
/// bare relative filename — normalise that to "." (an empty path breaks
/// `Command::current_dir`).
pub fn config_dir(config_path: &Path) -> PathBuf {
    match config_path.parent() {
        Some(p) if !p.as_os_str().is_empty() => p.to_path_buf(),
        _ => PathBuf::from("."),
    }
}

impl Config {
    pub fn load(path: &Path) -> Result<Config> {
        if !path.exists() {
            return Ok(Config::default());
        }
        let text =
            std::fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;
        toml::from_str(&text).with_context(|| format!("parsing {}", path.display()))
    }

    pub fn save(&self, path: &Path) -> Result<()> {
        // Merge into the existing file's table instead of overwriting it, so keys
        // written by a NEWER nixnas (or by hand) survive a round-trip through this
        // version. Comments and key order are NOT preserved — that would need
        // toml_edit, which is deliberately not pulled in for four fields.
        let mut table: toml::Table = if path.exists() {
            std::fs::read_to_string(path)
                .with_context(|| format!("reading {}", path.display()))?
                .parse()
                .with_context(|| format!("parsing {}", path.display()))?
        } else {
            toml::Table::new()
        };
        let own = toml::Value::try_from(self)
            .context("serialising config")?
            .as_table()
            .cloned()
            .unwrap_or_default();
        // `None` options serialise to NO key at all — remove them explicitly, or the
        // stale on-disk value would silently survive a "clear this field" edit.
        for key in ["sb_keys_sops", "build_memory_mib", "host_attr"] {
            if !own.contains_key(key) {
                table.remove(key);
            }
        }
        for (k, v) in own {
            table.insert(k, v);
        }
        let text = toml::to_string_pretty(&table).context("serialising config")?;
        std::fs::write(path, text).with_context(|| format!("writing {}", path.display()))
    }

    /// The flake directory, resolved against the config file's own directory.
    pub fn resolved_flake_dir(&self, config_path: &Path) -> PathBuf {
        let flake = Path::new(&self.flake_dir);
        if flake.is_absolute() {
            flake.to_path_buf()
        } else {
            config_dir(config_path).join(flake)
        }
    }
}
